# Generated by Django 4.1.1 on 2022-09-07 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('achievements', models.CharField(blank=True, max_length=256, null=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='media/')),
                ('daily_credit', models.IntegerField(default=10)),
                ('company_email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
